package core

import (
	"encoding/json"
	"fmt"
	"strings"
)

// Role identifies the speaker of a message in the conversation.
// Spec §2.2: User | Assistant (no separate "system" role — system
// content is carried separately on the request, not as a message).
type Role int

const (
	// RoleUser is a human-authored turn.
	RoleUser Role = iota
	// RoleAssistant is a model-authored turn.
	RoleAssistant
)

func (r Role) String() string {
	switch r {
	case RoleUser:
		return "user"
	case RoleAssistant:
		return "assistant"
	default:
		return fmt.Sprintf("role-%d", int(r))
	}
}

// ImageSource describes where an image's bytes come from.
// Spec §2.2 requires a "source" field on image blocks.
type ImageSource struct {
	// Type is "base64" (most common) or "url" (some providers).
	Type string `json:"type"`
	// MediaType is the MIME type, e.g. "image/png", "image/jpeg".
	MediaType string `json:"media_type,omitempty"`
	// Data is the base64-encoded bytes (for Type=="base64").
	Data string `json:"data,omitempty"`
	// URL is the image URL (for Type=="url").
	URL string `json:"url,omitempty"`
}

// ContentBlock is the tagged union of every kind of content that can
// appear in a message. Spec §2.2 lists: Text, Image, ToolUse, ToolResult,
// Thinking, RedactedThinking, Document.
//
// In Go, a tagged union is modeled as a struct with a Kind discriminator
// and kind-specific fields, plus accessor methods that return zero values
// for the "wrong" kind. The query loop and TUI use these accessors
// heavily — they should be O(1) and never panic.
type ContentBlock struct {
	// Kind discriminates the block type. Always set.
	Kind BlockKind `json:"type"`

	// Text is populated when Kind == BlockText.
	Text string `json:"text,omitempty"`

	// Image is populated when Kind == BlockImage.
	Image *ImageSource `json:"source,omitempty"`

	// ToolUse is populated when Kind == BlockToolUse.
	ToolUse *ToolUse `json:"tool_use,omitempty"`

	// ToolResult is populated when Kind == BlockToolResult.
	ToolResult *ToolResult `json:"tool_result,omitempty"`

	// Thinking is populated when Kind == BlockThinking.
	Thinking *Thinking `json:"thinking,omitempty"`

	// RedactedThinking is populated when Kind == BlockRedactedThinking.
	// Per spec, this carries opaque data the model emitted but that
	// we should not surface verbatim to the user.
	RedactedThinking json.RawMessage `json:"redacted_thinking,omitempty"`

	// Document is populated when Kind == BlockDocument.
	Document *Document `json:"document,omitempty"`
}

// BlockKind enumerates the content block types.
type BlockKind int

const (
	// BlockText is plain text content. Most common block.
	BlockText BlockKind = iota
	// BlockImage is an attached image (vision input).
	BlockImage
	// BlockToolUse is a model request to invoke a tool.
	BlockToolUse
	// BlockToolResult is the response to a prior ToolUse.
	BlockToolResult
	// BlockThinking is the model's chain-of-thought / extended reasoning.
	BlockThinking
	// BlockRedactedThinking is opaque reasoning content the vendor
	// redacted (e.g. for safety). We pass it back verbatim but don't
	// display it.
	BlockRedactedThinking
	// BlockDocument is a document attached to a user message, with
	// optional citation config.
	BlockDocument
)

// String returns a stable wire-format name for the block kind.
// These names match the spec's tagged-union labels.
func (k BlockKind) String() string {
	switch k {
	case BlockText:
		return "text"
	case BlockImage:
		return "image"
	case BlockToolUse:
		return "tool_use"
	case BlockToolResult:
		return "tool_result"
	case BlockThinking:
		return "thinking"
	case BlockRedactedThinking:
		return "redacted_thinking"
	case BlockDocument:
		return "document"
	default:
		return fmt.Sprintf("block-%d", int(k))
	}
}

// ToolUse is a model's request to invoke a tool. Input is raw JSON
// because each tool's input schema is different.
type ToolUse struct {
	// ID is the unique identifier for this tool call, generated by the
	// provider. The matching ToolResult references this ID.
	ID string `json:"id"`
	// Name is the tool name, e.g. "Bash", "Read", "Edit".
	Name string `json:"name"`
	// Input is the raw JSON object the model supplied. We keep it as
	// json.RawMessage so each tool can decode it into its own typed
	// input struct without a round-trip through map[string]any.
	Input json.RawMessage `json:"input"`
}

// ToolResult is the response to a prior ToolUse. Returned to the model
// as part of the next user message, paired with the ToolUse's ID.
type ToolResult struct {
	// ToolUseID is the ID of the ToolUse this is responding to.
	ToolUseID string `json:"tool_use_id"`
	// Content is the textual or structured result. We accept either a
	// plain string (most tools) or a list of ContentBlocks (for tools
	// that return images or other rich content). Stored as raw JSON
	// to preserve either shape.
	Content json.RawMessage `json:"content"`
	// IsError marks this result as a tool execution error rather than
	// a successful response. Per spec §3.1, errors never panic — they
	// become a ToolResult with IsError=true.
	IsError bool `json:"is_error,omitempty"`
}

// Thinking carries the model's extended-reasoning / chain-of-thought
// text. Visible to the user in the TUI (per spec §9.6 the companion's
// mood reacts to thinking blocks), and also returned to the model
// across turns to preserve reasoning continuity where the provider
// supports it.
type Thinking struct {
	// Text is the reasoning content.
	Text string `json:"thinking"`
	// Signature is a vendor-specific opaque blob that must be passed
	// back unchanged to preserve the reasoning thread. Anthropic uses
	// this; OpenAI does not. We carry it through transparently.
	Signature string `json:"signature,omitempty"`
}

// Document is a document attached to a user message (PDF, text file,
// etc.) with optional citation config. Spec §2.2.
type Document struct {
	Source      ImageSource    `json:"source"`
	Citations   *CitationConfig `json:"citations,omitempty"`
}

// CitationConfig controls how the model should cite the document.
type CitationConfig struct {
	Enabled bool `json:"enabled,omitempty"`
}

// TextBlock is a small constructor for a Text content block.
func TextBlock(text string) ContentBlock {
	return ContentBlock{Kind: BlockText, Text: text}
}

// ImageBlock is a small constructor for an Image content block.
func ImageBlock(src ImageSource) ContentBlock {
	return ContentBlock{Kind: BlockImage, Image: &src}
}

// ThinkingBlock is a small constructor for a Thinking content block.
func ThinkingBlock(text, signature string) ContentBlock {
	return ContentBlock{Kind: BlockThinking, Thinking: &Thinking{Text: text, Signature: signature}}
}

// MessageContent is the "either a string or a list of blocks" shape
// from spec §2.2. Modeled as a struct with a discriminator to avoid
// the ambiguity of `any` — a plain string is just a string, a list
// is a list of blocks, and there is no third case.
type MessageContent struct {
	// IsString is true when this is plain text. When true, use String.
	IsString bool
	// String is the text content when IsString.
	String string
	// Blocks is the list of content blocks when !IsString.
	Blocks []ContentBlock
}

// StringContent constructs a plain-text MessageContent.
func StringContent(s string) MessageContent {
	return MessageContent{IsString: true, String: s}
}

// BlocksContent constructs a list-of-blocks MessageContent.
func BlocksContent(blocks ...ContentBlock) MessageContent {
	return MessageContent{IsString: false, Blocks: blocks}
}

// GetFirstText returns the first Text block's content, or the
// string content if it's plain text, or "" if neither exists.
// Used by the TUI to display the message body's preview.
func (m MessageContent) GetFirstText() string {
	if m.IsString {
		return m.String
	}
	for _, b := range m.Blocks {
		if b.Kind == BlockText {
			return b.Text
		}
	}
	return ""
}

// AllText returns every Text block's content concatenated, separated
// by newlines. Plain string content returns that string as-is.
func (m MessageContent) AllText() string {
	if m.IsString {
		return m.String
	}
	var parts []string
	for _, b := range m.Blocks {
		if b.Kind == BlockText {
			parts = append(parts, b.Text)
		}
	}
	return strings.Join(parts, "\n")
}

// ToolUses returns every ToolUse block in the content, in order.
func (m MessageContent) ToolUses() []ToolUse {
	var out []ToolUse
	if m.IsString {
		return out
	}
	for _, b := range m.Blocks {
		if b.Kind == BlockToolUse && b.ToolUse != nil {
			out = append(out, *b.ToolUse)
		}
	}
	return out
}

// ThinkingBlocks returns every Thinking block in the content, in order.
func (m MessageContent) ThinkingBlocks() []Thinking {
	var out []Thinking
	if m.IsString {
		return out
	}
	for _, b := range m.Blocks {
		if b.Kind == BlockThinking && b.Thinking != nil {
			out = append(out, *b.Thinking)
		}
	}
	return out
}

// HasToolUse reports whether this content contains at least one ToolUse block.
func (m MessageContent) HasToolUse() bool {
	if m.IsString {
		return false
	}
	for _, b := range m.Blocks {
		if b.Kind == BlockToolUse {
			return true
		}
	}
	return false
}

// Message is a single turn in the conversation. Spec §2.2.
type Message struct {
	// Role is the speaker.
	Role Role `json:"role"`
	// Content is what was said. May be plain text or a list of blocks.
	Content MessageContent `json:"content"`
}

// NewUserText is a convenience for a plain-text user message.
func NewUserText(text string) Message {
	return Message{Role: RoleUser, Content: StringContent(text)}
}

// NewAssistantText is a convenience for a plain-text assistant message.
func NewAssistantText(text string) Message {
	return Message{Role: RoleAssistant, Content: StringContent(text)}
}

// NewUserBlocks is a convenience for a multi-block user message
// (e.g. one that carries image attachments or tool results).
func NewUserBlocks(blocks ...ContentBlock) Message {
	return Message{Role: RoleUser, Content: BlocksContent(blocks...)}
}

// NewAssistantBlocks is a convenience for a multi-block assistant message
// (text + thinking + tool_use blocks from one turn).
func NewAssistantBlocks(blocks ...ContentBlock) Message {
	return Message{Role: RoleAssistant, Content: BlocksContent(blocks...)}
}

// GetFirstText is a shortcut for m.Content.GetFirstText().
func (m Message) GetFirstText() string { return m.Content.GetFirstText() }

// AllText is a shortcut for m.Content.AllText().
func (m Message) AllText() string { return m.Content.AllText() }

// ToolUses is a shortcut for m.Content.ToolUses().
func (m Message) ToolUses() []ToolUse { return m.Content.ToolUses() }

// ThinkingBlocks is a shortcut for m.Content.ThinkingBlocks().
func (m Message) ThinkingBlocks() []Thinking { return m.Content.ThinkingBlocks() }

// HasToolUse is a shortcut for m.Content.HasToolUse().
func (m Message) HasToolUse() bool { return m.Content.HasToolUse() }

// UsageInfo is the per-turn token accounting. Spec §2.2.
type UsageInfo struct {
	// InputTokens is the number of input tokens this turn consumed.
	InputTokens int `json:"input_tokens"`
	// OutputTokens is the number of output tokens the model produced.
	OutputTokens int `json:"output_tokens"`
	// CacheCreationInputTokens is the number of input tokens that
	// populated the prompt cache this turn. Anthropic-specific.
	CacheCreationInputTokens int `json:"cache_creation_input_tokens,omitempty"`
	// CacheReadInputTokens is the number of input tokens served from
	// an existing cache entry this turn. Anthropic-specific.
	CacheReadInputTokens int `json:"cache_read_input_tokens,omitempty"`
}

// TotalInput returns the effective input token count: cache reads
// are still billable (just at a lower rate), so this is the number
// to multiply by the input price.
func (u UsageInfo) TotalInput() int {
	return u.InputTokens + u.CacheCreationInputTokens + u.CacheReadInputTokens
}

// Total returns every token accounted for in this turn.
func (u UsageInfo) Total() int {
	return u.TotalInput() + u.OutputTokens
}

// ToolDefinition describes a tool to the model. Spec §2.2.
type ToolDefinition struct {
	// Name is the tool's unique name (matches the tool registry).
	Name string `json:"name"`
	// Description is the human-readable description the model sees.
	Description string `json:"description"`
	// InputSchema is a JSON Schema describing the tool's input shape.
	// Stored as raw JSON so we can use encoding/json's schema generation
	// without a third-party JSON Schema library.
	InputSchema json.RawMessage `json:"input_schema"`
}
